language: node_js
node_js:
- '10'
repo_token: "$COVERALLS_TOKEN"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH=$HOME/.yarn/bin:$PATH
cache: false
git:
  depth: 5
script:
- yarn lint
- yarn test
after_success:
- yarn ci:coverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e4cbb72a5a86450bd6f5
    on_success: change
    on_failure: always
    on_start: never   
