language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"
git:
  depth: 5
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
script:
  - yarn run lint
  - yarn test
after_success: yarn run coverage